#!/bin/bash

# Quick Deployment Reference
# Copiar y ejecutar estos comandos en orden

echo "=== Guía Rápida de Despliegue Supabase ==="
echo ""
echo "Opción 1: Instalar Supabase CLI"
echo "================================"
echo "En Linux:"
echo "  brew install supabase/tap/supabase"
echo ""
echo "Luego ejecuta:"
echo "  npm run supabase:login"
echo "  npm run supabase:link"
echo "  npm run supabase:deploy"
echo ""
echo "Opción 2: Despliegue Manual (Sin CLI)"
echo "====================================="
echo "1. Abre el dashboard:"
echo "   https://app.supabase.com/project/faaqjsizafrszffotike/functions"
echo ""
echo "2. Nueva función:"
echo "   Name: make-server-4bdedad9"
echo "   Language: TypeScript (Deno)"
echo ""
echo "3. Copia el contenido de:"
echo "   supabase/functions/server/index.tsx"
echo ""
echo "4. Pega en el editor web y Deploy"
echo ""
echo "Verificar despliegue:"
echo "  curl https://faaqjsizafrszffotike.supabase.co/functions/v1/make-server-4bdedad9/health"
echo ""
echo "Ver logs:"
echo "  npm run supabase:logs"
